### PR TITLE
feat: Make crypto implementation pluggable.

### PR DESCRIPTION
**Pull request by ShogunPanda**
Hello.
This PR extracts all low level crypto interface in a specific file and makes the crypto interface pluggable in `Noise`.
Hope this helps!

### CODE REVIEW

**Review by mpetrunic — COMMENTED** [review]
Tnx for your contribution. Not a bad idea, will review in more detail next week

**Comment by ShogunPanda** [comment]
@mpetrunic Rebased and updated!

**Review by dapplion — COMMENTED** [review]
Looks good to me, nice abstraction! Are there any performance tests to ensure equal throughput? Results should be the same, but just to be sure

**Review by wemeetagain — APPROVED** [review]
LGTM from an organizational perspective

**Comment by mpetrunic** [comment]
> Looks good to me, nice abstraction! Are there any performance tests to ensure equal throughput? Results should be the same, but just to be sure

master
$ node benchmarks/benchmark.js
Initializing handshake benchmark
Init complete, running benchmark
handshake x 40.53 ops/sec ±17.26% (72 runs sampled)
Done in 6.54s.

PR#133
$ node benchmarks/benchmark.js
Initializing handshake benchmark
Init complete, running benchmark
handshake x 41.62 ops/sec ±15.59% (72 runs sampled)
Done in 6.39s.

It varies on each run but it's identical

**Comment by mpetrunic** [comment]
@dapplion This potentially allows you in lodestar to use some native library that might be faster than stablelib (purejs).

**Comment by dapplion** [comment]
> @dapplion This potentially allows you in lodestar to use some native library that might be faster than stablelib (purejs).

yeah looking forward to testing multiple impl

**Comment by ShogunPanda** [comment]
If you want, I have sample implementation with sodium-native in https://github.com/web3-storage/ipfs-elastic-provider-bitswap-peer/blob/main/src/noise-crypto.js

**Comment by dapplion** [comment]
> If you want, I have sample implementation with sodium-native in https://github.com/web3-storage/ipfs-elastic-provider-bitswap-peer/blob/main/src/noise-crypto.js

Let's goo! :fire: I you wanna contribute bringing this live in Lodestar I may airdrop some $LODE tokens in the future

**Comment by MarcoPolo** [comment]
I've implemented this interface with WASM using Rust and the `snow` crate: https://github.com/MarcoPolo/js-libp2p-noise-wasm

Here's some benchmarks:

Throughput:
```
❮ node dist/benchmark/src/index.js
TCP+mplex+noise
Download throughput is (mbits/s) 369n
Upload throughput is (mbits/s) 272n
TCP+yamux+noise
Download throughput is (mbits/s) 193n
Upload throughput is (mbits/s) 195n
TCP+mplex+wasm_noise
Download throughput is (mbits/s) 1047n
Upload throughput is (mbits/s) 1055n
TCP+yamux+wasm_noise
Download throughput is (mbits/s) 869n
Upload throughput is (mbits/s) 867n
```

Handshakes per second:

```
❮ node benchmarks/benchmark.js
Initializing handshake benchmark
Init complete, running benchmark
handshake x 632 ops/sec ±0.58% (89 runs sampled)
```

**Pull request merged**
