### PR TITLE
chore: update peer-id and libp2p-crypto

### PR DESCRIPTION
**Pull request by achingbrain**
Updates to the latest peer-id and libp2p-crypto.

No API changes, but libp2p-crypto removes some deps now that support for RSA in node core is better, though you need a modern node to use it.

BREAKING CHANGE: requires node 15+

### CODE REVIEW

**Review by dapplion — APPROVED** [review]
Thank you so much! That works well for Lodestar we are recommending running with Node v16 now

**Comment by achingbrain** [comment]
This will cause a conflict with #115 - I'm happy to resolve it when that happens but one of them needs merging first 😉

**Comment by dapplion** [comment]
Merged https://github.com/ChainSafe/js-libp2p-noise/pull/115 would you mind rebasing now?

**Comment by achingbrain** [comment]
This is still showing ci jobs running under node 14, even though ci for this PR has [completed successfully](https://github.com/ChainSafe/js-libp2p-noise/runs/4385088781?check_suite_focus=true).  Must be a gh actions oddity 🤷

**Comment by dapplion** [comment]
> This is still showing ci jobs running under node 14, even though ci for this PR has [completed successfully](https://github.com/ChainSafe/js-libp2p-noise/runs/4385088781?check_suite_focus=true). Must be a gh actions oddity shrug

Updated branch protection rules to no longer expect v14 runs

**Review by dapplion — APPROVED** [review]
Thank you so much!

**Review by wemeetagain — APPROVED** [review]

**Comment by achingbrain** [comment]
Thanks for merging - any chance of a release with this in please?

**Comment by wemeetagain** [comment]
:+1: PR for a new version here, release should follow after merging: https://github.com/ChainSafe/js-libp2p-noise/pull/119

**Comment by achingbrain** [comment]
It doesn't look like this has been released yet, npm still shows the latest as 4.1.1?

**Comment by wemeetagain** [comment]
Dang, the CI failed https://github.com/ChainSafe/js-libp2p-noise/runs/4409802719?check_suite_focus=true
I'll try to release now manually

**Comment by wemeetagain** [comment]
Ok, 5.0.0 should be released with https://github.com/ChainSafe/js-libp2p-noise/pull/120

**Pull request merged**
